### PR TITLE
HotFix Initial State for sandbox contract

### PR DESCRIPTION
**Pull request by ricklove**
Fix initial state for sandbox bootstrap: https://github.com/tqtezos/minter/issues/279

### CODE REVIEW

**Comment by ricklove** [comment]
Tested and this worked for me to allow sandbox to bootstrap

**Comment by mycodecrafting** [comment]
If the storage changed then the contract won’t work with minter ui at all. Not without other changes that we shouldn’t be randomly making right now. The real fix is to go back to the previous marketplace contract and put migrating to the newer version on the roadmap. Why was it suddenly changed in the first place?

**Comment by ricklove** [comment]
> If the storage changed then the contract won’t work with minter ui at all. Not without other changes that we shouldn’t be randomly making right now. The real fix is to go back to the previous marketplace contract and put migrating to the newer version on the roadmap. Why was it suddenly changed in the first place?

Not sure why the change was made, but here is where contract changes were made:

- https://github.com/tqtezos/minter/pull/278
- https://github.com/tqtezos/minter/pull/278/commits/654fb2ca80552587375c8a80f7fdf384be471406
- https://github.com/tqtezos/minter/pull/278/commits/2f1a8acbd8d3d1ffd7aa2a89dc9006b05032ecbe

**Comment by mycodecrafting** [comment]
> > If the storage changed then the contract won’t work with minter ui at all. Not without other changes that we shouldn’t be randomly making right now. The real fix is to go back to the previous marketplace contract and put migrating to the newer version on the roadmap. Why was it suddenly changed in the first place?
> 
> Not sure why the change was made, but here is where contract changes were made:
> 
> * #278
> * [654fb2c](https://github.com/tqtezos/minter/commit/654fb2ca80552587375c8a80f7fdf384be471406)
> * [2f1a8ac](https://github.com/tqtezos/minter/commit/2f1a8acbd8d3d1ffd7aa2a89dc9006b05032ecbe)

The newer version adds admin functionality. We’re not quite ready to implement those changes into the front end. We should change the marketplace to the previous one for now.

**Comment by ricklove** [comment]
> The newer version adds admin functionality. We’re not quite ready to implement those changes into the front end. We should change the marketplace to the previous one for now.

@obstropolos

Feel free to close this PR once you get the info you need.

**Comment by obstropolos** [comment]
Closing for now, fix handled in #280

**Pull request closed without merging**
