### PR TITLE
[3D]: Added draft support for 3d models (.obj, .gltf, .glb, .dae).

### PR DESCRIPTION
**Pull request by tchief**

### CODE REVIEW

**Review by ricklove — CHANGES_REQUESTED** [review]
This is a good start, but the TODO items need to be completed.

**Comment by zmnv** [comment]
@ricklove Can you use a great fast (on mobile) 3d viewer by google? it's awesome and used in hic.
https://modelviewer.dev/

**Comment by maelswarm** [comment]
#339

**Comment by obstropolos** [comment]
Closing this PR for now - we are adding support for 3D in a PR that is coming shortly.

**Pull request closed without merging**
