### PR TITLE
Carbon savings message on creation of NFT

### LINKED ISSUE #206: Carbon savings vs. Ethereum in UI
Add a small signpost during the minting period about how much carbon has been saved vs. minting the equivalent NFT on Ethereum.

https://memoakten.medium.com/the-unreasonable-ecological-cost-of-cryptoart-2221d3eb2053

### PR DESCRIPTION
**Pull request by obstropolos**
Added carbon savings message to token creation modal.

Screen Shot 2021-03-19 at 1 22 12 PM

Resolves #206

### CODE REVIEW

**Comment by jacobarluck** [comment]
@obstropolos , is that the precise copy / format of it?

**Comment by obstropolos** [comment]
@jacobarluck - yes shows up like that. Is there anything to change?

**Comment by jacobarluck** [comment]
"Creating token" is very close to the text about the carbon savings in that screenshot but may need to see it on an actual deployment.

**Comment by obstropolos** [comment]
Screen Shot 2021-03-19 at 9 43 35 PM

Added additional spacing.

**Comment by jacobarluck** [comment]
I think we should use 🌱 or similar instead of 💡

**Comment by obstropolos** [comment]
Screen Shot 2021-03-22 at 9 40 19 AM

Modified

**Comment by jacobarluck** [comment]
slight copy change proposal: "Minting on Tezos" instead of "Tezos minting"

**Review by mycodecrafting — APPROVED** [review]

**Pull request merged**
