### PR TITLE
Adds pagination to collection assets listing and collection

### PR DESCRIPTION
**Pull request by w4ll3**
This uses the offset properties of the BCD API to paginate the collection listing. Also fetches all the available collections on load, removing the current limit of 10 collection, as well 10 assets of a collection.
#239 is also fixed with this changes

### CODE REVIEW

**Comment by obstropolos** [comment]
This is great and working so far on my build (general) - would it be possible to put a spinner or loading indicator to show that it's in the process of pulling more data?

**Comment by ricklove** [comment]
Bug: I am not able to see any tokens in the minter featured collection:

image

**Review by ricklove — CHANGES_REQUESTED** [review]
Not seeing the pagination working.

**Comment by ricklove** [comment]
Bug: Only see 10 last added items in a collection:

image

**Comment by mycodecrafting** [comment]
In relation to the bug on this PR reported by @ricklove I will re-iterate what I stated in Slack earlier...

This PR does not work for me either. It doesn’t pull back all the big map entries. I can’t see my NFTs with it. It also doesn’t load the Minter NFTs on page load. And does some "on scroll" load more mechanic. Which wasn’t what this PR was supposed to be. In hindsight I should have done a better job explaining what we needed. I have updated the BCD code in the marketplace PR (#280) to pull all big map items which effectively resolves what the main goal of this PR was supposed to do.

Since PR #280 solves the main goal of what this PR was meant to do, I’d like to hold this one for now and revisit later. I think there is some useful stuff in here, but there’s also some stuff not needed and some stuff not working right. When things settle a bit, I will gather my thoughts on what those useful pieces are that I think we should pull out of here.

**Pull request closed without merging**
